# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Develop

pool:
  name: Default
  demands: java

steps:
- task: SonarQubePrepare@4
  displayName: 'Prepare sonar analysis for Angular code'
  inputs:
    SonarQube: Sonarqube
    scannerMode: CLI
    configMode: manual
    cliProjectKey: 'POC-Angular'
    cliProjectName: 'POC-Angular'
    cliSources: '.\Angular8Cosmos'

- task: SonarQubeAnalyze@4
  displayName: 'Run Code Analysis for Angular Code'

- task: SonarQubePrepare@4
  displayName: 'Prepare analysis on SonarQube for API project'
  inputs:
    SonarQube: Sonarqube
    scannerMode: CLI
    configMode: manual
    cliProjectKey: 'POC-API'
    cliProjectName: 'POC-API'
    cliSources: '.\TenantAPI'

- task: SonarQubeAnalyze@4
  displayName: 'Run Code Analysis for API'
